apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso
  namespace: documenso
  labels:
    app: documenso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso
  template:
    metadata:
      labels:
        app: documenso
    spec:
      containers:
        - name: documenso
          image: documenso/documenso:v1.12.1
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_SECRET
              value: super-secret-key
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_API_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_WEBAPP_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_MARKETING_URL
              value: http://localhost:3000
            - name: NEXT_PRIVATE_DATABASE_URL
              value: postgresql://myuser:mypass@postgres-service.postgres.svc.cluster.local:5432/documenso
            - name: NEXT_PRIVATE_DIRECT_DATABASE_URL
              value: postgresql://myuser:mypass@postgres-service.postgres.svc.cluster.local:5432/documenso
            - name: NEXT_PRIVATE_SMTP_FROM_NAME
              value: Documenso
            - name: NEXT_PRIVATE_SMTP_FROM_ADDRESS
              value: no-reply@documenso.local
            - name: NEXT_PRIVATE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: NEXT_PRIVATE_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: NEXT_PRIVATE_S3_REGION
              value: us-east-1
            - name: NEXT_PRIVATE_S3_BUCKET
              value: documenso
            - name: NEXT_PRIVATE_S3_ENDPOINT
              value: http://minio.documenso.svc.cluster.local:9000
