apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso
  namespace: documenso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso
  template:
    metadata:
      labels:
        app: documenso
    spec:
      containers:
        - name: documenso
          image: ghcr.io/documenso/documenso:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypass@postgres-service.postgres:5432/mydb"
            - name: NEXT_PRIVATE_DATABASE_URL
              value: "postgresql://myuser:mypass@postgres-service.postgres:5432/mydb"
            - name: NEXT_PRIVATE_DIRECT_DATABASE_URL
              value: "postgresql://myuser:mypass@postgres-service.postgres:5432/mydb"
            - name: NEXTAUTH_SECRET
              value: "super-secret-string"
            - name: NEXTAUTH_URL
              value: "http://localhost:3000"
          ports:
            - containerPort: 3000
