apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso
  namespace: documenso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documenso
  template:
    metadata:
      labels:
        app: documenso
    spec:
      containers:
        - name: documenso
          image: ghcr.io/documenso/documenso:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypass@postgres-service.postgres:5432/mydb"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: STORAGE_DRIVER
              value: "s3"
            - name: S3_ENDPOINT
              value: "http://minio.documenso:9000"
            - name: S3_BUCKET
              value: "documenso"
            - name: S3_ACCESS_KEY
              value: "minioadmin"
            - name: S3_SECRET_KEY
              value: "minioadmin"
            - name: NEXTAUTH_SECRET
              value: "secret123"
            - name: NEXTAUTH_URL
              value: "http://documenso.local"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: documenso
  namespace: documenso
spec:
  selector:
    app: documenso
  ports:
    - port: 3000
      targetPort: 3000
