apiVersion: v1
kind: Secret
metadata:
  name: documenso-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://documenso:documenso123@postgres-service.postgres.svc.cluster.local:5432/documenso
  STORAGE_DRIVER: s3
  STORAGE_ENDPOINT: http://minio.documenso.svc.cluster.local:9000
  STORAGE_BUCKET: documenso
  STORAGE_REGION: us-east-1
  STORAGE_ROOT_USER: admin
  STORAGE_ROOT_PASSWORD: minioadmin
