apiVersion: v1
kind: Service
metadata:
  name: documenso
  namespace: documenso
  labels:
    app: documenso
spec:
  type: NodePort
  selector:
    app: documenso
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
