apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort                     # 🟢 Change from ClusterIP to NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30900               # You can choose any available port (30000-32767)
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901
