apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
data:
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_PORT: "5678"  # ✅ correct
  N8N_BASIC_AUTH_PASSWORD: "adminpass"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "postgres-service.postgres.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8ndb"
  DB_POSTGRESDB_USER: "myuser"
  DB_POSTGRESDB_PASSWORD: "mypass"
  N8N_HOST: "n8n.yourdomain.com"
  WEBHOOK_URL: "https://n8n.yourdomain.com"
