# neo4j-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.19
          ports:
            - containerPort: 7474   # HTTP
            - containerPort: 7687   # Bolt
          env:
            - name: NEO4J_AUTH
              valueFrom:
                configMapKeyRef:
                  name: neo4j-config
                  key: NEO4J_AUTH
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-pvc
